layout(local_size_x = 128) in;

#include <fluid.glsl>

layout(std430, binding = 1) volatile coherent restrict buffer ParticleBuffer {
	Particle particleData[];
};

layout(rgba32f, binding = 0) uniform readonly image3D volume;

uniform vec3 b_min;
uniform vec3 b_max;

uniform float deltaTime = 0;
uniform ivec2 resolution;

ivec3 directions[] = {
	ivec3(-1, -1, -1),
	ivec3(-1, -1, 1),
	ivec3(-1, 1, -1),
	ivec3(-1, 1, 1),
	ivec3(1, -1, -1),
	ivec3(1, -1, 1),
	ivec3(1, 1, -1),
	ivec3(1, 1, 1),
};

void main() {
	uvec3 invID = gl_GlobalInvocationID;
	if(invID.x >= N) return;
	uint id = invID.x;

	Particle p1 = particleData[id];

	p1.velocity = vec3(0);
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[0] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[1] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[2] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[3] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[4] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[5] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[6] + ivec3(10)).xyz;
	p1.velocity += imageLoad(volume, ivec3(floor(p1.position)) + directions[7] + ivec3(10)).xyz;
	p1.velocity /= 8.0f;

	particleData[id] = p1;
}
