layout(local_size_x = 128) in;

#include <fluid.glsl>

layout(std430, binding = 1) restrict readonly buffer ParticleBuffer {
	Particle particleData[];
};

layout(binding = 2) restrict writeonly buffer Hashes {
	uint hashData[];
};


void main() {
	uvec3 invID = gl_GlobalInvocationID;
	uint id = invID.x;

	if(id >= N) {
		return;
	}

	Particle p1 = particleData[id];

	hashData[2 * id] = spatialHash(p1.position);
	hashData[2 * id + 1] = id;
}
