name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: configure
      run: cmake -S ./ -B ./build/ -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    - name: make
      run: cmake --build ./build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
