name: Compile Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y libxrandr-dev libxinerama-dev xorg-dev libglu1-mesa-dev
    - name: configure
      run: cmake -S ./ -B ./build/ -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
    - name: make
      run: cmake --build ./build -j4
    - name: test
      run: cmake --build ./build --target=test
